// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Broadcast.proto


public class RoomLobby
{
    public int LobbyStatue;

    public bool RoomStatue;

    public bool ClientStatue;

}

