// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Broadcast.proto


public class Broadcast
{
    public string IPAddress;

    public int Port;

}

